name: CI

on:
  push:
    tags:
      - "test-*"

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
          manylinux: auto
      - name: pytest
        if: ${{ startsWith(matrix.target, 'x86_64') }}
        shell: bash
        run: |
          set -e
          pip install bloomlib --find-links dist --force-reinstall
          pip install coverage codecov pytest
          coverage run --source=bloomlib -m pytest -s test/
          coverage report
          coverage xml
          codecov -t "${{ secrets.CODECOV_TOKEN }}" --commit="${GITHUB_SHA}" --branch="master"
#      - name: pytest
#        if: ${{ !startsWith(matrix.target, 'x86') && matrix.target != 'ppc64' }}
#        uses: uraimo/run-on-arch-action@v2.5.0
#        with:
#          arch: ${{ matrix.target }}
#          distro: ubuntu22.04
#          githubToken: ${{ github.token }}
#          install: |
#            apt-get update
#            apt-get install -y --no-install-recommends python3 python3-pip
#            pip3 install -U pip pytest
#          run: |
#            set -e
#            pip3 install bloomlib --find-links dist --force-reinstall
#            pytest